### ISSUE TITLE
If I delete the website I thought the resource would be deleted from here but its not?

### ISSUE THREAD

**Issue by cansavvy** [fhdsl/DaSL_Collection#20]
I archived the old DataTrail modules such as: https://github.com/datatrail-jhu/03_fileorganization and deleted their websites that were linked in the description. 

I thought because I deleted the website that meant when DaSL_Collection re-ran it would delete the content from the listing but it does not appear to do that? 

<img width="969" alt="Screen Shot 2023-05-02 at 2 35 58 PM" src="https://user-images.githubusercontent.com/23458084/235755256-a8fb15cf-c788-4315-b6c2-ea9610a2158e.png">

**Comment by avahoffman** [comment]
Thanks for raising this. Looks like the builds are failing because of that fun github repo issue.

**Comment by avahoffman** [comment]
@cansavvy Has this been fixed now that the render is running correctly?

**Comment by cansavvy** [comment]
Yes! That's more what I expected! Thanks.
