### ISSUE TITLE
Separating software from courses

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSL_Collection#24]
To make it easier for people to find courses, we are going to separate out the edtech software - we could make a new table for that later maybe, but for now thinking of dropping these from the table and showing icons and links to the major software websites instead: loqui, ottr, metricminer (maybe others if they have websites). 

To do so I (and Kate) am adding the tag [edtech-software](https://github.com/topics/edtech-software) on all repos that are about edtech-software so we can split these out from the course table.

**Comment by carriewright11** [comment]
also added [hutch-course](https://github.com/topics/hutch-course) as a tag for hutch branded courses

**Comment by avahoffman** [comment]
Add icons to brand anvil, itcr, hutch, etc

**https://www.opencasestudies.org/OCS_search/**

**Comment by carriewright11** [comment]
This is done!
